addpath(genpath(fullfile(...
	'..', '..', '..', '..', '..', '..', '..', '..', 'beamforming_code', 'image_quality_metrics', 'utils')));

load_data;

sys_ab_precision_vec = zeros(size(vivo_time_mat, 1), 1);
sys_ab_recall_vec = zeros(size(sys_ab_precision_vec));
sys_ab_f1_score_vec = zeros(size(sys_ab_precision_vec));

sys_c_precision_vec = zeros(size(vivo_time_mat, 1), 1);
sys_c_recall_vec = zeros(size(sys_c_precision_vec));
sys_c_f1_score_vec = zeros(size(sys_c_precision_vec));

for i0 = 1:size(vivo_time_mat, 1)
	p0 = vivo_id_vec(i0);

	[...
		sys_ab_precision_vec(i0), sys_ab_recall_vec(i0), sys_ab_f1_score_vec(i0), ...
		sys_c_precision_vec(i0), sys_c_recall_vec(i0), sys_c_f1_score_vec(i0)] = computePrecisionMetrics(...
		vivo_sys_ab_struct(p0), vivo_sys_c_struct(p0), vivo_time_mat(i0, :));
end

fprintf('\n');
fprintf('\\begin{tabular}{clrrrr}\n');
fprintf('\\toprule\n');
fprintf('\\multicolumn{1}{c}{\\multirow{2}{*}{\\textbf{System}}} ');
fprintf('& \\multicolumn{1}{c}{\\multirow{2}{*}{\\textbf{Performance Metric}}} ');
fprintf('& \\multicolumn{4}{c}{\\textbf{Trial Number}} \\\\\n');
fprintf('\\multicolumn{2}{}{} & 1 & 2 & 3 & 4 \\\\ \\midrule\n');
fprintf(...
	'\\multirow{4}{*}{\\textbf{DetectionNet}} & Recall [\\%%] & %.1f & %.1f & - & - \\\\\n', ...
	100.0 .* sys_ab_recall_vec(1), 100.0 .* sys_ab_recall_vec(2));
fprintf(...
	' & Precision [\\%%] & %.1f & %.1f & - & - \\\\\n', ...
	100.0 .* sys_ab_precision_vec(1), 100.0 .* sys_ab_precision_vec(2));
fprintf(...
	' & F1 Score [\\%%] & %.1f & %.1f & - & - \\\\ \\midrule\n', ...
	100.0 .* sys_ab_f1_score_vec(1), 100.0 .* sys_ab_f1_score_vec(2));
fprintf(...
	'\\multirow{4}{*}{\\textbf{WaveSegNet-1}} & Recall [\\%%] & - & - & %.1f & %.1f \\\\\n', ...
	100.0 .* sys_ab_recall_vec(3), 100.0 .* sys_ab_recall_vec(4));
fprintf(...
	' & Precision [\\%%] & - & - & %.1f & %.1f \\\\\n', ...
	100.0 .* sys_ab_precision_vec(3), 100.0 .* sys_ab_precision_vec(4));
fprintf(...
	' & F1 Score [\\%%] & - & - & %.1f & %.1f \\\\ \\midrule\n', ...
	100.0 .* sys_ab_f1_score_vec(3), 100.0 .* sys_ab_f1_score_vec(4));
fprintf(...
	'\\multirow{3}{*}{\\textbf{WaveSegNet-2}} & Recall [\\%%] & %.1f & %.1f & %.1f & %.1f \\\\\n', ...
	100.0 .* sys_c_recall_vec);
fprintf(' & Precision [\\%%] & %.1f & %.1f & %.1f & %.1f \\\\\n', 100.0 .* sys_c_precision_vec);
fprintf(' & F1 Score [\\%%] & %.1f & %.1f & %.1f & %.1f \\\\ \\bottomrule\n', 100.0 .* sys_c_f1_score_vec);
fprintf('\\end{tabular}\n');
