% Set up a figure for nine tiles arranged in a 3x3 format.
set(...
	0, ...
	'defaultlinelinewidth', 3, ...
	'defaultaxesfontsize', 14, ...
	'defaultlinemarkersize', 7, ...
	'defaulterrorbarlinewidth', 3);

figure(1);
set(gcf, 'Position', [100, 10, 1500, 460]);
tiledlayout(1, 3, 'Padding', 'loose', 'TileSpacing', 'compact');

